services:
  dev:
    image: ghcr.io/wpelevator/ngx-cache-pilot--dev:${NGINX_VERSION:-1.25.5}
    build:
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.25.5}
    working_dir: /workspace
    volumes:
      - .:/workspace
  packaging:
    image: ghcr.io/wpelevator/ngx-cache-pilot--packaging:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.packaging
    working_dir: /workspace
    volumes:
      - .:/workspace
